# Generated by Django 5.0.3 on 2024-08-06 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_ip',
            field=models.CharField(max_length=255),
        ),
    ]
